### ISSUE TITLE
Creating ants and letting them run for a while results in an error

### ISSUE THREAD

**Issue by marcbue** [BCCN-Prog/2019_elegANT#44]
![grafik](https://user-images.githubusercontent.com/44844855/58880415-1bdc6f80-86d8-11e9-969f-85a4d9e70db8.png)

**Comment by DorotheaMueller** [comment]
From the kd_tree_and_dict:

if new_position is not None:
    self.all_objects.setdefault(tuple(new_position), []).append(item)

Running the test with type(tuple(new_position)) gives tuple object as expected. 
The error happens if more ants are created. Could you please theck that the new_position that is returned is always an numpy array with two elements so it can be casted as a tuple?

**Comment by marcbue** [comment]
Current pull request includes a fix but new error arises:

![grafik](https://user-images.githubusercontent.com/44844855/58973669-cc25a300-87c0-11e9-9e34-738c1043d27e.png)

**Comment by marcbue** [comment]
should be fixed
